version: '2'

services:
  wp:
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    domainname: ${DOMAIN}
    ports:
      - "80:80" # change ip if required
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full wordpress project
      - ./theme-base/:/var/www/html/wp-content/themes/theme-base # Theme development
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db

  wpcli:
    image: wordpress:cli
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    depends_on:
      - db
      - wp

  db:
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - "3306:3306" # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

  ## testing
  node:
    image: "node:8"
    user: "node"
    working_dir: /var/www/html
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/var/www/html
    expose:
      - "8081"
    command: "npm start"
  ## testing
  
  gulp:
    image: ellerbrock/alpine-gulp-sass:latest
    volumes:
      - ${DIR_SASS}:/sass
      - ${DIR_CSS}:/css
    environment:
      - SASS=${FILES_SASS}
      - CSS=${DIR_CSS}
      - - GULP_DEBUG=${GULP_DEBUG}
    networks:
      - webdev


networks:
  webdev:
    driver: bridge

volumes:
  db_data:
